# Executive Summary

<!--
This section provides a condensed view of the entire proposal, one page long.
It should be a comprehensive high-level overview that captures the essence of the proposal, including its goals, methods, expected outcomes, deliverables, and budget.
-->

This proposal seeks to ameliorate three challenges facing the R-spatial ecosystem.

First, spatial analysis in R "is slow" and can be dramatically improved. The de facto package for vector-based spatial analysis in R is the {sf} package. Due to its ergonomic API and its integration with the tidyverse, it is the common choice for spatial data analysis. However, {sf} can struggle to scale effectively and has caused developers to turn to other tools and other languages.

Secondly, the past few years have seen the rapid adoption of Apache Arrow—a standard for in-memory representation of arrays and tables. The spatial ecosystem, in particular, has been quick to adopt GeoArrow, an extension fo the Arrow standard that defines how spatial data can be represented with Apache Arrow.

The standardization on (Geo)Arrow enables the development of pacakges that can work on in-memory data without incurring any additional overhead costs of deserializing and seriailzing data into intermediate objects.

Lastly, concurrent to the development of GeoArrow has been the development of GeoParquet. At present, GeoParquet support in R has focused on consuming the format. To my knowledge, there is no R package that provides tailored support for writing GeoParqeut as well as reading from remote storage.

I seek $5,000 USD to fund the completion of the development of a new Rust-based, GeoArrow native, and highly performent spatial computation engine for R called {geoarrowrs}.
The R package will provide:

- GeoArrow-native and parallelized computation engine
- Persistent spatial RTree and KDTree spatial indexes for efficient spatial querying and joining
- Drop in compatibility with {sf}
- Enhanced GeoParquet support such as spatial sorting, bounding boxes on row-chunks for predicate pushdown, and persisting coordinate reference systems.
